### ISSUE TITLE
Compile code

### ISSUE THREAD

**Issue by folny** [Frans-Willem/EspLightNode#11]
Hi

Can you tell me what should I do so that I can compile code using ESPRESSIF DEVKIT FOR WINDOWS ? thanks.

http://www.esp8266.com/viewtopic.php?f=9&t=820&sid=408be0e0d99c971272ece64195b6aa87

**Comment by Frans-Willem** [comment]
I don't have a windows box handy at this moment, but I'll try to look into it later.

**Comment by folny** [comment]
Ok thanks for your reply so that the code can compile only under Linux ?.

**Comment by Frans-Willem** [comment]
At this point I have only tested on Linux, but I will install a windows box later to try and compile on windows too.
I'll keep you posted :)

**Comment by folny** [comment]
Ok thanks :-)

**Comment by Frans-Willem** [comment]
Hey,

I've taken some time to debug under Windows, and I can tell you that with the toolchain you linked it won't compile, sorry.
The initial error of strcasecmp is an easy fix, but what lies beyond is much worse. Seeing as the project is C++ and rather big, I set it up in such a way that only a very small portion will be loaded beforehand, and most of the code will be loaded from the SPI ROM (which has more space available). Unfortunately, to allow function calling between those two sections you need the -mlongcalls flag to g++, which was apparently not done when compiling the C++ standard library that is shipped with this toolchain.

It's a shame the toolchain maker didn't open-source the scripts he used, as it would probably be an easy fix at that point. However, at this point there isn't much I can do for you :(
I suppose your best bet is a Linux VM. The compiler and libraries I use are in https://github.com/Frans-Willem/arch-esp8266-packages as ArchLinux packages, you could use those on ArchLinux (use makepkg), or simply read through PKGBUILD and use the commands in there to compile your own things. I also suspect the more traditional crosstool-NG toolchain will work, provided you use the C++ version on jcmvbkbc's github.

Once this project reaches a somewhat more usable state (and I'm getting there), I will put pre-compiled binaries for download.
