### ISSUE TITLE
add a way to go back to defauld config if something going wrong

### ISSUE THREAD

**Issue by jblb** [Frans-Willem/EspLightNode#17]
First test with a node configured as client of AP1. now I have not access to AP1 and I can't access to EspNode.
a way coul'd be a time out if not connected

**Comment by Frans-Willem** [comment]
Try esptool.py --port /dev/ttyUSB0 erase_flash, and then reflashing EspLightNode.

Pulling up a SoftAP when there's no connection would mean that when my WiFi goes down for a moment all my EspLightNodes would revert to standard config :/
I agree there should be a way, but I'm not quite sure what'd be the best way...

**Comment by Frans-Willem** [comment]
Added a clearconfig option to the Makefile. Does that help?

**Comment by jblb** [comment]
> Try esptool.py --port /dev/ttyUSB0 erase_flash, and then reflashing 
> EspLightNode.
> 
> thats what i do for now and it's works
> 
> Pulling up a SoftAP when there's no connection would mean that when my 
> WiFi goes down for a moment all my EspLightNodes would revert to 
> standard config :/
> I agree there should be a way, but I'm not quite sure what'd be the 
> best way...
> 
> No i thinking only on startup: if unable to connect configured AP set in 
> mode*AP+STA so we could connect to node and setup new AP

---

## 

@+
jérôme
htpp://jblb.net
