### ISSUE TITLE
Web EspLightNode Configuration didn't always save data

### ISSUE THREAD

**Issue by jblb** [Frans-Willem/EspLightNode#18]
when change are made in the web UI they are not always saved, and sometime everything  go back to default value.

**Comment by Frans-Willem** [comment]
Is there any way you can reproduce this error ?
e.g. is it with specific values, or with specific browser, or is there any other way to trigger it?

**Comment by jblb** [comment]
hi,
i do much with Firefox and lynx on few linux box but did not find a way to reproduce error or not in a predictive way.
i finaly suspect my network topology here.
i think we can close this issue

**Comment by Frans-Willem** [comment]
Alright, feel free to open another if you can somehow reproduce it :)
