### ISSUE TITLE
How can i use this files ?

### ISSUE THREAD

**Issue by ghost** [Frans-Willem/EspLightNode#2]
Hi,

I think it would be great to replace my old AVR Art-Net node with a esp8266.
What do i need to compile  your code ?

Thanks in advance.
(Sorry for my english, its bad....)

**Comment by Frans-Willem** [comment]
Hey,

Sorry for the late response.
As is, this code is not ready to be used. However, if you'd like to compile it, just use the ESP8266 toolchain and adjust the Makefile to point to wherever the xtensa GCC compiler is and the SDK is located.
