### ISSUE TITLE
tpm2net not working (release ver 0.2)

### ISSUE THREAD

**Issue by fladdie** [Frans-Willem/EspLightNode#25]

**Comment by Frans-Willem** [comment]
TPM2.Net with Glediator appears to be working.

Could you let me know what you're testing with?

**Comment by Frans-Willem** [comment]
Oh, almost forgot:

Thank you for reporting back! It's really encouraging to see the software actually being used by people :) :+1:

**Comment by Frans-Willem** [comment]
I double checked with v0.2 and Glediator v2.0.3, and TPM2.net works for me. I believe it might be configuration issue on your end.
Would you be able to check with something like WireShark if Glediator is sending the right packets?
They should be sent to port 65506.
