### ISSUE TITLE
Questions to get it running - in Station/Client mode

### ISSUE THREAD

**Issue by giovanne123** [Frans-Willem/EspLightNode#27]
Hi Frans-Willem,
I'm very interested in your solution.
Some questions and how to get this running?
- is it possible to run EspLightNode (v0.2) in Client/Station mode, so that it grabs automatic an IP via DHCP from my router? How to set client mode? [I have already flashed the precompiled v0.2 bins and actually can see/connect to the AP EspLightNodeXXXX]
- are there settings which can be configured via ESP-Website?
- for me it is very difficult to setup the build env, but I will try (some doc therefore would be fine ;-)
  If I have to compile the source to get into client mode, can you please compile me a binary version which I can flash to my two ESPs.

Thank your very much !!! ;-)

My plan is to: have a Pi running with hyperion and tmp2net support. This sends data to the EspLightNode. But EspLightNode has to run in client mode and therefore accessible in my local network vi IP.

Maybe if I'm familiar with all this, I can help to document your project ;-)

**Comment by fladdie** [comment]
Hi Giovanne,

first, yes you can run it in client mode with DCHP. You can change the Settings via Webinterface.
After you have flashed v2 to your ESP you have to connect to the AP EspLightNodeXXXX.
Then you have to browse to the IP Adress of the AP via your Browser to change settings via Webinterface.

Further steps should be self-explanatory.

**Comment by jblb** [comment]
Hi,
I'm not Frans-Willem but I'll try to answer you questions

Le 19/01/2016 10:52, giovanne123 a écrit :

> - is it possible to run EspLightNode (v02) in Client/Station mode, so
>   that it grabs automatic an IP via DHCP from my router? How to set
>   client mode? [I have already flashed the precompiled v02 bins and
>   actually can see/connect to the AP EspLightNodeXXXX]
> - are there settings which can be configured via ESP-Website?
>   yes it can be runing as a client, you can change the setup on
>   ESP-Website First Frame (WiFi Operation mode)

## 

@+
jérôme
http://jblb.net

**Comment by giovanne123** [comment]
Hi fladdie and jblb,

thank you very much. This is the answer I'm waiting for ;-)
I will try it today evening at home and report here.

Are you both using the EspLightMode for your own? Is it working well (with ws2801)?

And have you setup a build env for compiling yourself? If yes, can someone descripe the steps for that?

**Comment by fladdie** [comment]
Hi giovanne,

it is working with ws2801 and also with ws2812 without any Problem. I dont no if the Problems with tmp2net solved already. But with artnet evereything is running fine!

A step by step tutorial of building the env would be very nice!

**Comment by jblb** [comment]
Hi,

> A step by step tutorial of building the env would be very nice!

if you could setup an arch linux distro (for example on a VM) you can
follow https://github.com/Frans-Willem/arch-esp8266-packages

## 

@+
jérôme
http://jblb.net

**Comment by giovanne123** [comment]
VM Image like this one for example: http://sourceforge.net/projects/osboxes/files/vms/vmware/Arch_Linux/2015/201507/archlinux_201507-32bit.7z/download
I hope to get this running. With the follow up instructions from Frans-Willem... https://github.com/Frans-Willem/arch-esp8266-packages

Otherwiese a port to Arduino IDE would be interesting, or (because there is already a Arduino IDE mit ESP8266 Addons: https://github.com/esp8266/Arduino)?

**Comment by giovanne123** [comment]
@fladdie,
"I dont no if the Problems with tmp2net solved already. But with artnet evereything is running fine!"
What problems are there using tpm2net with EspLightNode? 
Edit: OK after reading issues/threads, it seams that you have problems with Jinx, but Frans successful tested with gladiator. I will try by testing it on my ESP this evenening...

Do you know is artnet supported by hyperion?

**Comment by giovanne123** [comment]
Ok thanks so far. ESP-01 running in Station/Client mode connected to my local network ;-)
Now I have to put my ws2801 led strip to the ESP. Edit: Done in SPI Bitbang mode.
1. One question from the config page, for the ws2801 led strip, what is the difference between HSPI or SPI Bitbang, or will both normally work? 
   Edit: I think I have to use SPI Bitbang because I will connect the DATA/CLCK to GPIO 2/0 and this could be configured there.
2. And one more question for the ESP firmware: How is the Debugging in the firmware used?
3. Tried testing the ws2801 led strip with Jinx/Glediator. Seems to be also complex :-(
   What is working.
   a) After setup output device in Jinx to tpm2net and select "Start output", The strip is reacting and I think a predefined effect on the ESP is started (random LEDs/Colors started). Deactivating "Start output" stops random effect.
   But I can't get something selected in Jinx effect (e.g. Simple Color) displayed on the LEDs/ESP :-( 
   What could be wrong? (I thinks the ESP/ws2801 at all is working because of the random effect)

b) also tried glediator, but there I don't know how to configure the tpm2net (where to put the IP...). I set output mode to TPM2_Net, and select OpenSocket. Result "TPM2.Net socket open".
But no (ESP buildin) random effect is started. And also can't get something to the LEDs/ESP...

c) maybe I will try a test with artnet also, but I have to read how to configure before...

Sorry for the long descriptions/text, but it is a little bit complicated and maybe when I get it running I can document a little bit for others to get it running easier ;-)

I hope someone could help a little bit.

**Comment by giovanne123** [comment]
@fladdie,
if I want to use artnet, what do I have to configure in the webpage for:
- Net:  (IP from ESP-10) ?
- Sub: (255.255.255.0) ?
- Universe: (0) ?

**Comment by jblb** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi,

Le 20/01/2016 16:00, giovanne123 a écrit :

> @fladdie https://github.com/fladdie, if I want to use artnet,
> what do I have to configure in the webpage for:
> - Net: (IP from ESP-10) ? \* Sub: (255.255.255.0) ? \* Universe: (0)
>   ?

If you use only one node you can configure it as
Net : 0
SubNet: 0
Universe : 0

if you got more than one device increment Universe

---

@+
jérôme
http://jblb.net
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.17 (GNU/Linux)

iQEcBAEBAgAGBQJWn688AAoJELfBan+yggskjScIAMj1ONtRG7KlSu44m6KIQ9VG
w4Q5/rpGpmf1JlKmQooTye0rSTruEIF8tA5SL0cF9zSwgeF42/FKojQtoElnoWta
J433zrkighGT+CUoz9/BupY2pnHYf5TLCBR0xS7FE9j79qxSrV6vx2phCJRx0MNN
yG/o+dKRgNfErbqjDZvD/6fyGS/dmrt+YLXrUcMNwbUSlJVALQxSIb5BNd7M2pUu
8U3hRIb1TUZuu27RX5d5DgaV/0nmiJi4nOKMKeSJF6PX9UTFpAV6Y6S1DkLAhjqG
OzPSBP+3ETbCxcNo4qkan7w4YxXJnGk4E2J3VJa1f2VACMAdTalsxaa056iHwKI=
=eggJ
-----END PGP SIGNATURE-----

**Comment by giovanne123** [comment]
Ok, some output to the ws2801 strip.
Jinx and Glediator at the moment are to complicated for me :-(
But with PixelController is was able to get the output from PixelController via ESP to the ws2801 - yea ;-)
But only with ArtNet.
With tpm2net I was not able to get something to the ws2801.

Ok, if tpm2net isn't working in v0.2 I have to go on with Artnet maybe and have to search if there is a hyperion (ambilight) patch/support using artnet.

For the other functions in the EspLightNode firmware I can say that it is very good, and running very stable with wifi over the hole day ;-)

**Comment by giovanne123** [comment]
Hi fladdie or someone else,
in this issue-thread you wrote that it is working well with ws2812(b) also.
Do you have ws2812 running with EspLightNode?
I can't get it working using ws2812b with ESP :-(
How have you connected the ws2801 and how configured on the website?

I hope get it working. It is working already so well with my ws2801 strips.

Thanks
giovanne

**Comment by giovanne123** [comment]
Hi fladdie or someone else,
do you have ESPLightNode working with ws2812(b) also?
I can't get it working with ws2812. With ws2801 it is working fantastic.
How to connect ws2812 and how to configure via website?
Thanks

**Comment by giovanne123** [comment]
OK - ws2812(b) are working. For I2S I have to connect LED-Data to Rx on the ESP-01 ;-)

Only one issue for me.
Blue and Red a inversed/cross changed :-(
Hope to find a config for this...
