### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by jblb** [Frans-Willem/EspLightNode#3]
unable to compile with last version of ESP8266 open sdk

got this:

user/config/httpd.cpp: In function 'void httpd_process_header(HttpdConnectionSlot_, uint8_t_, uint16_t)':
user/config/httpd.cpp:139:46: error: 'strcasecmp' was not declared in this scope
  if (strcasecmp((char *)line,"Content-length")) {

**Comment by Frans-Willem** [comment]
I think I'm using a different newlib/libc implementation to yours. Try replacing all occurences of strcasecmp to strcmpi or stricmp.
The newlib I'm using is: https://github.com/projectgus/newlib-xtensa

Did that help ?

**Comment by jblb** [comment]
Hi,
replacing all occurences of strcasecmp to strcmpi or stricmp didn't help.
i now have a look to https://github.com/projectgus/newlib-xtensa but can't figure how to build it for ESP8266.

**Comment by Frans-Willem** [comment]
Hey, I think the easiest solution for you would be to get libc  from the esp8266 wiki github, and link with those:
https://github.com/esp8266/esp8266-wiki/blob/master/libs/libc.a
https://github.com/esp8266/esp8266-wiki/blob/master/include.tgz

untar that include directory, then adjust the Makefile to add an -I../wherever/you/unpacked/include and a -L/wherever/you/put/the/libc/file. I think that should work.

**Comment by jblb** [comment]
even with that i unable to compiling the code
here is the result of a make in a fresh pulled directory (SDK var in makefile ajusted ) http://pastebin.com/VkyzmvNw

**Comment by Frans-Willem** [comment]
I'll spin up a virtual machine with the official SDK and see if I can get it working :)

**Comment by Frans-Willem** [comment]
Alright, I've done some troubleshooting, and apparently strcasecmp should be defined in strings.h instead of string.h. My latest commit fixes that for you.
I compiled on a clean ArchLinux virtual machine, with the needed dependencies install, and these were my exact steps:

``` bash
cd ~
git clone https://github.com/jcmvbkbc/crosstool-NG -b lx106-g++-1.21.0
cd crosstool-NG/
./bootstrap
./configure --prefix=`pwd` && make && make install
./ct-ng xtensa-lx106-elf
./ct-ng build
cd ~
wget -O sdk.zip "http://bbs.espressif.com/download/file.php?id=664&sid=b345c0e0de94700e2189b83ed2d786a8"
unzip sdk.zip
cd ~
git clone https://github.com/themadinventor/esptool
cd esptool
sed -i 's/python/python2/' esptool.py
cd ~
git clone https://github.com/Frans-Willem/EspLightNode
cd EspLightNode
PATH=~/crosstool-NG/builds/xtensa-lx106-elf/bin:~/esptool/:$PATH make SDK=~/esp_iot_sdk_v1.3.0
```

Let me know if that helps!

**Comment by jblb** [comment]
Hi,
With you instructions it's compile fine. It's load OK but no answer in my arnet set-up, need more investigations...

**Comment by Frans-Willem** [comment]
Did you notice that it was still a work in progress ?
It's nowhere near a complete working project at this point :-/
I'm currently putting a lot of effort in a HTTP configuration interface, and saving settings. After that I'll return to the more functional programming.
In it's current state WS2801 support _might_ work, but don't pin me down on that :/

**Comment by jblb** [comment]
Hi again !
Yes i noticed it's a work in progress, but in my remember it's working even it wasn't easy to configure, this why a give it a try as a HTTP configuration interface being implemented.
As i'm not a software guy i can't help much :-/

**Comment by Frans-Willem** [comment]
Feel free to star the repository so you get updates whenever I commit new stuff :)
